name: Test workflow-cps-global-lib-http-plugin

on: [push, pull_request]

jobs:

  ci-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Bump version and push tag
      id: versioning
      uses: anothrNick/github-tag-action@1.8.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: fabricepipart
        RELEASE_BRANCHES: master
    - name: Build Maven
      env:
        VERSION: ${{ steps.versioning.outputs.new_tag }}
      run: |
        mvn -B -U versions:set -DnewVersion=${VERSION} &> /dev/null
        mvn -B -U clean verify
    - uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: javaplugin
        name: codecov-java-plugin

  ci-windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Maven
      run: |
        mvn -B -U clean verify

  ci-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Maven
      run: |
        mvn -B -U clean verify

